### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by Erick555**
- Remove redundant openssh which is avalaible in runtime
- Install git in smart way to save massive amount of app size.

### CODE REVIEW

**Comment by Erick555** [comment]
bot, build

**Comment by Erick555** [comment]
Installed app size went down from 782.8 MB to 409.4 MB after this changes.

**Comment by Erick555** [comment]
@eighthave ping

**Comment by Erick555** [comment]
@eighthave thx for merging although the repo build [failed due to unrelated reasons](https://flathub.org/builds/#/builders/10/builds/3843) so those changes won't be published until this is fixed.

**Comment by eighthave** [comment]
@Erick555 that 404 issue is fixed now on the f-droid.org server, can you 
retrigger the build?

**Comment by Erick555** [comment]
@eighthave only collaborators can retrigger builds however after recent commits there are new errors introduced: https://flathub.org/builds/#/builders/35/builds/3852 . After you commit fixes then new build covering all previous changes will be published automatically (assuming the build succeeds).

**Pull request merged**
