### PR TITLE
Bump sip to 4.19.13

### PR DESCRIPTION
**Pull request by cpba**

### CODE REVIEW

**Comment by AltNico** [comment]
Thanks for your continuous work, @cpba! I CCed you [in the last MR on GitLab](https://gitlab.com/fdroid/fdroid-repomaker-flatpak/merge_requests/23) in hope you see this part I added to the README:
> Development of this flatpak happens at gitlab.com/fdroid/fdroid-repomaker-flatpak. Once it's considered stable, it'll be pushed to the repo at github.com/flathub/org.fdroid.Repomaker.

I just [merged your commit into GitLab](https://gitlab.com/fdroid/fdroid-repomaker-flatpak/commit/48c8a9e48a90a093b78aecfb29a6ab1bf901ce0e) but did not push it yet to flathub because of the missing functionality tests. If you, however, tested the build, you can state this in the MRs and I'll push them to flathub, too.

By the way, if you are interested in helping out maintaining Repomaker for Flatpak, I can get you advanced privileges on this repo and on GitLab's one so that you can self merge if it's simple stuff like this one. I for my part would highly appreciate help from your side on this :slightly_smiling_face:

**Comment by cpba** [comment]
@AltNico Sorry, I knew you had merged the repo but I didn't see there was a new part on the readme.

Yes I tested the build locally before submitting the pull request, the flathub test build also finished successfully and is available for testing: http://repo-test.flathub.org:8080/build-repo/380/org.fdroid.Repomaker.flatpakref

It was my idea to at least help out somewhat it maintaining the manifest, but I don't have all that much time and I don't know how much I'll be able to do. I'll get set up on gitlab.

**Comment by AltNico** [comment]
@cpba Thanks for testing. So I pushed the commit to Flathub, too.

> It was my idea to at least help out somewhat it maintaining the manifest

That's great, thank you!

> I don't have all that much time and I don't know how much I'll be able to do

With this you make no difference from all other F-Droid contributors ;) Do as much as you can and want, but there's no need to have a bad conscience if you don't do anything for some time. Every help, as little as it is, is highly appreciated!

@grote So I added @cpba as developer to [fdroid/fdroid-repomaker-flatpak](https://gitlab.com/fdroid/fdroid-repomaker-flatpak/project_members).

@cpba With @grote and also with other F-Droid contributors we agreed on doing everything through merge requests, so everyone included in the development gets a mail about a change. Therefore I enabled for persons of type "developer" like you to only allow them to merge merge requests. That means you aren't allowed to push directly to `master`, but you shouldn't have any need to do so anyway. But feel free to directly self-merge tinier changes like your last two PRs!

As for this repository, I'm not sure on how to continue on this. Ideally, I would like to have integration/functionality tests in GitLab CI, so that every commits gets fully build and tested in GitLab and if everything goes well, that gets directly pushed to Flathub. But so far, we haven't got those integration tests.

I guess the best solution for the moment is that @grote or I regularly push updates from GitLab to GitHub and if you, @cpba, feel like we should push something, you can always ping us and one of us will do.

Welcome aboard :slightly_smiling_face:

**Comment by AltNico** [comment]
@cpba Ah, another two things:
* Pre-configured GitLab CI runners have a time quota, so it could happen that you're no more allowed to use them for the rest of a month if you're working to heavily on Repomaker's flatpak. To get around that limit, you can [get yourself a GitLab CI runner](https://gitlab.com/fdroid/admin/issues/106) hosted by F-Droid.
* If you every have a question around F-Droid, feel free to drop by #fdroid-dev on FreeNode or [#fdroid-dev:f-droid.org](https://matrix.to/#/#fdroid-dev:f-droid.org) on Matrix/Riot.

**Pull request closed without merging**
