### PR TITLE
Bump pyqt5 to version 5.11.3

### PR DESCRIPTION
**Pull request by cpba**

### CODE REVIEW

**Comment by AltNico** [comment]
@cpba Thanks!

Do I understand this correctly that this change will be included in Flathub once I push a new version to Repomaker's appdata and update that file in our build script here? Or will this change immediately get included in Flathub, i.e. a new version of the current release will be published?

Seeing [the build I just triggered](http://repo-test.flathub.org:8010/#/builders/6/builds/373), I'm thinking the latter happens. But I've absolutely no idea.

**Comment by barthalion** [comment]
No, you don't to update appdata, every commit triggers a build.

**Comment by barthalion** [comment]
(So yes, it's a new build of current release.)

**Comment by cpba** [comment]
Any new commit to master triggers a rebuild and gets published as the
newest version.

The version numbers in the appdata files are good to inform users of the
particular release they have installed, but don't serve any purpose from a
technical standpoint.

**Comment by AltNico** [comment]
@barthalion @cpba Ah, thanks. Good to know. So we have to care with every change that we don't break the existing flatpak. We should probably run automated integration tests on the flatpak then, specific to Repomaker.

**Comment by cpba** [comment]
Sure, more testing is always better.

However, keep in mind that the buildbot will automatically make a test
build of any pull request. Also, even if you were to merge a broken commit,
the new version won't be pushed if the build fails, its bad but it isn't
*that* catastrophic.

**Pull request merged**
